substitutions:
  name: "localbytes-bulb-9w-rgbct"
  friendly_name: "Local Bytes RGBCT Bulb"

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: jamesswift.localbytes-bulb-9w-rgbct
    version: "0.0.1"

esp8266:
  board: esp8285
  restore_from_flash: true

ota:

wifi:
  output_power: 14db
  power_save_mode: light
  ap:
    ssid: "${friendly_name}"
  
captive_portal:

dashboard_import:
  package_import_url: github://JamesSwift/localbytes-bulb-9w-rgbct/localbytes-bulb-9w-rgbct.yaml
